#include "book_management.h"
#include<string.h>
struct node
{
	Book Book;
	struct node* next;
};
struct ar
{
	BookArray BookArray;
	struct _BookArray *next;
};
	struct node* head, *tail;
	head->next=NULL;
	struct ar *h, *t;
	h->next = NULL;
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file)
{
	if(head != NULL)
  { 
    struct node *p = head->next;
    FILE* fp = fopen(file, "w+");
    if(fp != NULL)
    {
      while(p != NULL)
      {
        fprintf(fp, "%d %s %s %d %d\n", p->Book.id,p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
        p = p->next;
      }
      fclose(fp);
      return 0; 
    }
	else {
      
      error("fail to open the txt.Please check!\n");
    }  
  }
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
load_books(FILE *file)
{
	FILE* fp = fopen(file, "a+");
  Book book;
  if (fp != NULL) {
    while (fscanf(fp, "%d %s %s %d %d", &Book.id, &Book.title, &Book.author, &Book.year, &Book.copies) != EOF) 
	{
      if(head != NULL)
  		{
			Book *node;
			node = (struct Book *)malloc(sizeof(Book));
			node=Book;
			node = node->next;
			if(node != NULL)
    		{
      		struct node* p = head;
      		while(p->next != NULL)
        	p = p->next;
			p->next = node;
    		}
  		}
    }
    fclose(fp);
    return 0;
  }

  else 
  {
    error("fial to open the txt.Please check!\n");
  }
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
add_book(Book book)
{
	int i=0;
	int j=0;
	struct node *node1;
	node1 = (struct Book *)malloc(sizeof(Book));
	printf("Enter the title of the book you wish to add:");
	scanf("%s",&node1->Book.title);
	printf("Enter the author of the book you wish to add:");
	scanf("%s",&node1->Book.authors);
	printf("Enter the year that the book you wish to add was released:");
	scanf("%d",&node1->Book.year);
	printf("Enter the number of the copies of the book that you wish to add:");
	scanf("%d",&node1->Book.copies);
	struct node *a=head;
	while(a->next==NULL)
	{
	j++;
	if(strcmp(node->Book.title,a->Book.title)==NULL)
	{
		printf("Book has been added successfully!");
	}
	else
	{
	a = a->next;
	i++;
	}
	}
	if(i==j)
	{
		node->Book.id = j;
		tail->next = node;
		tail = tail->next;
		printf("Book was successfully added!");
		return 0;
	}
}
//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
remove_book(Book book)
{
	struct node *p = head;
	while(p.next.Book==book)
	{
		p=p->next;
	}
	if(p->next->Book==book)
	{
	struct node* pr=p->next; 
	p->next=pr->next;
	free(pr);
	return 0;
	}
	else
	return 1;
}

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title (const char *title)
{
	ar *k=h; 
	k = (struct BookArray *)malloc(sizeof(struct BookArray));
	node *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->Book.title,title)==0)
		{
			ar->BookArray.length=length+1;
			while(k->next==NULL)
			{
				k=k->next;
			}
			k->BookArray.array=p->Book;
		}
		p=p->next;
	}
	return ar->BookArray; 
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author (const char *author)
{
	ar *k=h; 
	k = (struct BookArray *)malloc(sizeof(struct BookArray));
	node *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->Book.author,author)==0)
		{
			ar->BookArray.length=length+1;
			while(k->next==NULL)
			{
				k=k->next;
			}
			k->BookArray.array=p->Book;
		}
		p=p->next;
	}
	return ar->BookArray; 
}
//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year (unsigned int year)
{
	ar *k=h; 
	k = (struct BookArray *)malloc(sizeof(struct BookArray));
	node *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->Book.year,year)==0)
		{
			ar->BookArray.length=length+1;
			while(k->next==NULL)
			{
				k=k->next;
			}
			k.BookArray->array=p->Book;
		}
		p=p->next;
	}
	return ar->BookArray; 
}
