#include "book_management.h"
#include<string.h>
	Book* head, *tail;
	head->next=NULL;
	Book* h,t;
	
//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file)
{
	if(head != NULL)
  { 
    Book *p = head->next;
    FILE* fp = fopen(file, "w+");
    if(fp != NULL)
    {
      while(p != NULL)
      {
        fprintf(fp, "%d %s %s %d %d\n", p->id,p->title, p->authors, p->year, p->copies);
        p = p->next;
      }
      fclose(fp);
      return 0; 
    }
	else {
      
      error("fail to open the txt.Please check!\n");
    }  
  }
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
load_books(FILE *file)
{
	FILE* fp = fopen(file, "a+");
  Book* book;
  if (fp != NULL) {
    while (fscanf(fp, "%d %s %s %d %d", &book->id, &book->title, &book->authors, &book->year, &book->copies) != EOF) 
	{
      if(head != NULL)
  		{
			Book *node;
			node = (struct Book *)malloc(sizeof(Book));
			node=book;
			node = node->next;
			if(node != NULL)
    		{
      		Book* p = head;
      		while(p->next != NULL)
        	p = p->next;
			p->next = node;
    		}
  		}
    }
    fclose(fp);
    return 0;
  }

  else 
  {
    error("fial to open the txt.Please check!\n");
  }
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
add_book(Book book)
{
	int i=0;
	int j=0;
	Book *node1;
	node1 = (struct Book *)malloc(sizeof(Book));
	printf("Enter the title of the book you wish to add:");
	scanf("%s",&node1->title);
	printf("Enter the author of the book you wish to add:");
	scanf("%s",&node1->authors);
	printf("Enter the year that the book you wish to add was released:");
	scanf("%d",&node1->year);
	printf("Enter the number of the copies of the book that you wish to add:");
	scanf("%d",&node1->copies);
	Book *a=head;
	while(a->next==NULL)
	{
	j++;
	if(strcmp(node1->title,a->title)==NULL)
	{
		printf("Book has been added successfully!");
	}
	else
	{
	a = a->next;
	i++;
	}
	}
	if(i==j)
	{
		node1->id = j;
		tail->next = node1;
		tail = tail->next;
		printf("Book was successfully added!");
		return 0;
	}
}
//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
remove_book(Book book)
{
	int i;
	Book *p = head;
	printf("Enter the ID number of the book you wish to remove:");
	scanf("d%",&i);
	while(p->next->id==i)
	{
		p=p->next;
	}
	if(p->next->id==i)
	{
	Book* pr=p->next; 
	p->next=pr->next;
	free(pr);
	printf("Book was successfully removed");
	return 0;
	}
	else
	return 1;
}

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title (const char *title)
{
	BookArray BookArray;
	Book *k=h; 
	BookArray.array=h;
	k = (struct Book *)malloc(sizeof(Book));
	Book *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->title,title)==0)
		{
			BookArray.length++;
			k=p;
			while(k->next==NULL)
			{
				k=k->next;
			}
		}
		p=p->next;
	}
	return BookArray; 
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author (const char *author)
{
	BookArray BookArray;
	Book *k=h; 
	BookArray.array=h;
	k = (struct Book *)malloc(sizeof(Book));
	Book *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->authors,author)==0)
		{
			BookArray.length++;
			k=p;
			while(k->next==NULL)
			{
				k=k->next;
			}
		}
		p=p->next;
	}
	return BookArray;
}
//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year (unsigned int year)
{
	BookArray BookArray;
	Book *k=h; 
	BookArray.array=h;
	k = (struct Book *)malloc(sizeof(Book));
	Book *p= head;
	while(p->next!=NULL)
	{
		if (strcmp(p->year,year)==0)
		{
			BookArray.length++;
			k=p;
			while(k->next==NULL)
			{
				k=k->next;
			}
		}
		p=p->next;
	}
	return BookArray;
}


